DDT-1079 - Modulize it
dcsaorg/DCSA-Shared-Kernel pull request #19
Opened 2022-05-27 13:39 UTC by FinnAtAsseco

2022-05-27 14:11 UTC, nt-as submitted a review, later dismissed

2022-05-30 05:56 UTC, pimg requested changes

2022-05-30 05:56 UTC, pimg commented on pom.xml
> +		<module>shared-kernel-pagination</module>
pagination can go into infrastructure, no need for separate module

2022-05-30 05:56 UTC, pimg commented on pom.xml
> +		<module>shared-kernel-persistence</module>
Persistence can be renamed to domain

2022-05-30 05:56 UTC, pimg commented on pom.xml
> +		<module>shared-kernel-validation</module>
validation can go into infrastructure

2022-05-30 05:56 UTC, pimg commented on pom.xml
> +		<module>shared-kernel-http-headers</module>
http headers can go into infrastructure

2022-05-30 05:56 UTC, pimg commented on pom.xml
> +		<module>shared-kernel-errors-transfer-obj</module>
all error modules can be consolidated into 1

2022-05-30 09:15 UTC, pimg approved these changes

2022-05-30 09:16 UTC, merged